version: '3.8'

services:
  # Web API Service
  create-ticket-api:
    image: 975050117852.dkr.ecr.us-west-2.amazonaws.com/eventmgmt:create-ticket-api
    build:
      context: .
      dockerfile: CreateTicketApi/Dockerfile
    ports:
      - "5220:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs/worker:/app/logs
    depends_on:
      - redis-cache
    restart: always

  # Background Service (Worker)
  worker-service:
    image: 975050117852.dkr.ecr.us-west-2.amazonaws.com/eventmgmt:email-scheduler-worker
    build:
      context: .
      dockerfile: EmailSchedulerWorker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - redis-cache
    restart: always

  # Redis Cache Service
  redis-cache:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
