version: '3.8'

services:
  # Web API Service
  create-ticket-api:
    image: 975050117852.dkr.ecr.us-west-2.amazonaws.com/eventmgmt:create-ticket-api
    build:
      context: .
      dockerfile: CreateTicketApi/Dockerfile
    ports:
      - "5220:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- AWS_PROFILE=SC  # Specify which profile to use
      # - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=yourdb;Uid=root;Pwd=password;
      # - Redis__ConnectionString=redis-cache:6379
    volumes:
      # Mount AWS credentials from Windows host to Linux container
      - ${HOME}/.aws:/root/.aws:ro
    depends_on:
      - redis-cache

  # Background Service (Worker)
  worker-service:
    image: 975050117852.dkr.ecr.us-west-2.amazonaws.com/eventmgmt:email-scheduler-worker
    build:
      context: .
      dockerfile: EmailSchedulerWorker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- AWS_PROFILE=SC
      # - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=yourdb;Uid=root;Pwd=password;
      # - Redis__ConnectionString=redis-cache:6379
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
    depends_on:
      - redis-cache

  # Redis Cache Service
  redis-cache:
    platform: linux/amd64
    image: redis:latest
    ports:
      - "6379:6379"
