<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EmailSchedulerWorker-cdeece62-84e7-48e0-b91d-0737a0f122b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="4.0.2.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />

  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EventDbAccess\EventDbAccess.csproj" />
    <ProjectReference Include="..\EventUtils\EventUtils.csproj" />
  </ItemGroup>
</Project>
